/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 apple.gltf 
Author: MysteryPancake (https://sketchfab.com/mysterypancake)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-logo-ec021e3e50774b02937823e0a6145500
Title: Apple Logo
*/

import React, {Suspense, useRef} from 'react';
import { useGLTF, Environment, PerspectiveCamera } from '@react-three/drei';
import  {Canvas, useFrame}  from '@react-three/fiber';
import CanvasLoader from './Loader'; 

function Model(props) {
  const { nodes, materials } = useGLTF('/3d/apple.gltf');

  const ref = useRef();

  useFrame(({ clock }) => {
    if (ref.current) {
      ref.current.rotation.y = clock.getElapsedTime() * 0.5; // Adjust speed as needed
    }
  });

  return (
    <group {...props} dispose={null} ref={ref} scale={10}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Apple_0.geometry} material={materials['1976logo']} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

export default function Apple(){
  return(
    <Canvas style={{ height: '300px', width: '300px' }}> {/* Ajustez la taille si nécessaire */}
      <PerspectiveCamera
        makeDefault
        position={[0, 0, 75]} // Ajustez la position si nécessaire
        fov={75}
        near={0.1}
        far={1000}
      />
      <ambientLight intensity={0.5} />
      <directionalLight position={[10, 10, 10]} intensity={1} />
      <Environment preset="sunset" />
      <Suspense fallback={<CanvasLoader />}>
        <group rotation={[0, Math.PI / 4, 0]}>
          <Model position={[0, 0, 0]} scale={[0.5, 0.5, 0.5]} />
        </group>
      </Suspense>
    </Canvas>
  );

}


useGLTF.preload('/apple.gltf')
