/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 windows.gltf 
Author: tg (https://sketchfab.com/tgaaaaaaaaaa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/windows-logo-e22e1e1fc71640ecb14b1b29a92da2b2
Title: Windows Logo
*/

import React, {Suspense, useRef} from 'react';
import { useGLTF, Environment, PerspectiveCamera } from '@react-three/drei';
import  {Canvas, useFrame}  from '@react-three/fiber';
import CanvasLoader from './Loader'; 

function Model(props) {
  const { nodes, materials } = useGLTF('/3d/windows.gltf');

  const ref = useRef();

  useFrame(({ clock }) => {
    if (ref.current) {
      ref.current.rotation.y = clock.getElapsedTime() * 0.5; // Adjust speed as needed
    }
  });

  return (
    <group {...props} dispose={null} ref={ref} scale={0.5}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.color_15277357} position={[0, 11.495, 31.505]} />
    </group>
  )
}

export default function Windows(){
  return(
    <Canvas style={{ height: '300px', width: '300px' }}> {/* Ajustez la taille si nécessaire */}
      <PerspectiveCamera
        makeDefault
        position={[0, 0, 75]} // Ajustez la position si nécessaire
        fov={75}
        near={0.1}
        far={1000}
      />
      <ambientLight intensity={0.5} />
      <directionalLight position={[10, 10, 10]} intensity={1} />
      <Environment preset="sunset" />
      <Suspense fallback={<CanvasLoader />}>
        <group rotation={[0, Math.PI / 4, 0]}>
          <Model position={[0,  18, 0]} scale={[0.5, 0.5, 0.5]} />
        </group>
      </Suspense>
    </Canvas>
  );

}
useGLTF.preload('/windows.gltf')
